.TH spacefm-scripts 7 "May 2022"

.SH NAME
.B spacefm-scripts-sys

.SH DESCRIPTION
Internal SpaceFM scripts
.P

.SH SCRIPTS
    config-update

    config-update-git

    spacefm-auth



.SH OVERRIDES
User modified versions of these scripts can be supplied in
"~/.config/spacefm/script-overrides". These scripts must contain the same
calling interface as the scripts provided by this package.


.SH SEE ALSO
.BR spacefm (1)
.br
.BR spacefm-design-menu (7)
.br
.BR spacefm-devices (7)
.br
.BR spacefm-gui (7)
.br
.BR spacefm-handlers (7)
.br
.BR spacefm-plugins (7)
.br
.BR spacefm-scripts (7)
.br
.BR spacefm-scripts-sys (7)
.br
.BR spacefm-socket (7)
.br
.BR spacefm-tasks (7)
.PP
