.TH SPACEFM 1 "July 11, 2013"
.SH NAME
spacefm \- multi-panel tabbed file manager.
.SH SYNOPSIS
.B spacefm
[\fIOPTION\fR]... [\fIDIR | FILE | URL\fR]...
.SH OPTIONS
.TP
.B \-t, \-\-new-tab
Open folders in new tab of last window (default)
.TP
.B \-r, \-\-reuse-tab
Open folder in current tab of last used window
.TP
.B \-n, \-\-no\-saved\-tabs
Don't load saved tabs
.TP
.B \-w, \-\-new\-window
Open folders in new window
.TP
.B \-p, \-\-panel=P
Open folders in panel 'P' (1-4)
.TP
.B \-\-no\-desktop
No function - for compatibility only
.TP
.B \-\-desktop
Launch desktop manager daemon
.TP
.B \-\-desktop\-pref
Show desktop settings
.TP
.B \-\-desktop\-pref=N
Show Preferences ('N' is the Pref tab number)
.TP
.B \-d, \-\-daemon\-mode                                                                                                                                                                 
Run as a daemon
.TP
.B \-c, \-\-config\-dir=DIR                                                                                                                                                                 
Use DIR as configuration directory
.TP
.B \-f, \-\-find\-files                                                                                                                                                                 
Show File Search
.TP
.B \-\-set\-wallpaper
Set desktop wallpaper to FILE
.TP
.B \-g, \-\-dialog
Show a custom dialog (See -g help)
.TP
.B \-\-s, \-\-socket\-cmd
Send a socket command (See -s help)
.TP
.B \-p, \-\-profile=<profile>
No function - for compatibility only
.TP
.B \-\-version
Show version information
.TP
.B \-\-display=DISPLAY
X display to use
.TP
.B \-h, \-\-help
Show summary of options.
.SH AUTHOR
spacefm was written by IgnorantGuru <ignorantguru@gmx.com>
.PP
This manual page was written by Mateusz Łukasik <mati75@linuxmint.pl>,
for the Debian project (and may be used by others).
