.TH SPACEFM-AUTH 1 "June 24, 2013"
.SH NAME
spacefm\-auth \- This script is used internally by spacefm and is not designed to be run directly.
.TP
.B \-h, \-\-help
Show summary of options.
.SH AUTHOR
spacefm was written by IgnorantGuru <ignorantguru@gmx.com>
.PP
This manual page was written by Mateusz Łukasik <mati75@linuxmint.pl>,
for the Debian project (and may be used by others).
